apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: reusable
on:
  workflow_call:
    inputs:
      targetenv:
        type: string
     
    secrets:
      testsec:
        required: false

jobs:



  # This should fail if the environment passed as param does not exist, but work if environment is environment_mlcb_test_param
  testinheritance_env_param:
    environment: ${{ inputs.targetenv }}
    steps:
      - name: Print testsec 
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "testsec: ${{ secrets.testsec }} is this masked? hardcode"

