apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: reusable
on:
  workflow_call:
    inputs:
      targetenv:
        type: string
        required: false
    secrets:
      testsec2:
        required: false

jobs:
  # testhardcoded1:
  #   environment: environment_mlcb_test_param
  #   steps:
  #     - name: Print testvar
  #       uses: docker://golang:1.20.3-alpine3.17
  #       shell: sh
  #       run: |
  #         echo " do I get the approval ?"

  # testparamenv1:
  #   environment: ${{ inputs.targetenv }}
  #   steps:
  #     - name: Print testvar
  #       uses: docker://golang:1.20.3-alpine3.17
  #       shell: sh
  #       run: |
  #         echo " do I get the approval ?"

  
  # testhardcoded:
  #   environment: ${{ 'environment_mlcb_test_param' }}
  #   steps:
  #     - name: Print testvar
  #       uses: docker://golang:1.20.3-alpine3.17
  #       shell: sh
  #       run: |
  #         echo "testvar: ${{ vars.testvar }}"
  #     - name: Print testsec
  #       uses: docker://golang:1.20.3-alpine3.17
  #       shell: sh
  #       run: |
  #         echo "testvar: ${{ secrets.testsec }}"

  testparamenv:
    environment: ${{ inputs.targetenv }}
    steps:
      - name: Print env
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "environment: ${{ inputs.targetenv }}"
      - name: Print testvar
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "testvar: ${{ vars.testvar }}"
      - name: Print testsec2
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "testsec2: ${{ secrets.testsec2 }} and hardcode ????"


    
