apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: reusable
on:
  workflow_call:
    inputs:
      targetenv:
        type: string

jobs:

  testinheritance_checkout:
    steps:
      - name: checkout
        uses: cloudbees-io/checkout@v1
  
