apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: reusable
on:
  workflow_call:
    inputs:
      targetenv:
        type: string

jobs:

  testinheritance_checkout:
    steps:
      - name: use action
        uses: cloudbees-io/checkout@v1
      - name: use preconf-action
        uses: mlcb_checkout
  
